config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :incomes, only: [:new ,:create]
  resources :expenditures, only: [:new ,:create]
  resources :diffs, only: [:index]

  root 'transactions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '水道代' },
    { id: 3, name: '光熱費' },
    { id: 4, name: '食費' },
    { id: 5, name: '日用品' },
    { id: 6, name: 'カード払い' },
    { id: 7, name: 'その他' },
  ]
  include ActiveHash::Associations
  has_many :expenditures
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :user

  validates :category_id, numericality: { other_than: 1 } 
  validates :expenditure_amount, presence: true,
                    numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 9_999_999 }
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :user

  validates :income_amount, presence: true,
                    numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 9_999_999 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :incomes
  
  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/differences_controller.rb
class DifferencesController < ApplicationController
  def index
  end
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  def index
  end

  def new
    @expenditure = Expenditure.new
  end

  def create
    @expenditure = Expenditure.new(expenditure_params)
    if @expenditure.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def expenditure_params
    params.require(:expenditure).permit(:category_id,:expenditure_amount,:register_day).merge(user_id: current_user.id)
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def index
  end

  def new
    @income = Income.new
  end

  def create
    @income = Income.new(income_params)
    if @income.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def income_params
    params.require(:income).permit(:income_amount,:register_day).merge(user_id: current_user.id)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @income = Income.all
    @expenditure = Expenditure.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/differences_helper.rb
module DifferencesHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/differences/index.html.erb
<h1>Differences#index</h1>
<p>Find me in app/views/differences/index.html.erb</p>

app/views/expenditures/index.html.erb
<h1>Expenditures#index</h1>
<p>Find me in app/views/expenditures/index.html.erb</p>

app/views/expenditures/new.html.erb
<h1>支出の登録</h1>

<%= form_with model: @expenditure, url: expenditures_path do |form| %>
  <p>
    カテゴリー<br>
    <%= form.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"shop-category"}) %>
  </p>
  <p>
    支出金額<br>
    <%= form.number_field :expenditure_amount %>
  </p>
  <p>
    日付<br>
    <%= form.date_select :register_day %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/incomes/index.html.erb
<h1>Incomes#index</h1>
<p>Find me in app/views/incomes/index.html.erb</p>

app/views/incomes/new.html.erb
<h1>収入の登録</h1>

<%= form_with model: @income, url: incomes_path do |form| %>
  <p>
    収入金額<br>
    <%= form.number_field :income_amount %>
  </p>
  <p>
    日付<br>
    <%= form.date_select :register_day %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneyManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<header class="header">
  <div class="inner">
    <div class="nav">
      <div class="nav__left">
        <%= link_to image_tag("logo_transparent.png", class: "logo"), root_path %>
      </div>
      <% if user_signed_in? %>
        <div class="nav__right">
          <%= link_to current_user.nickname, "#", class: "user-nickname" %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav__logout" %>
          <%= link_to "収入を登録", new_income_path, class: "nav__btn" %>
          <%= link_to "支出を登録", new_expenditure_path, class: "nav__btn" %>
        </div>
      <% else %>
        <div class="nav__right">
          <%= link_to "ログイン", new_user_session_path, class: "nav__btn" %>
          <%= link_to "新規登録", cancel_user_registration_path, class: "nav__btn" %>
        </div>
      <% end %>
    </div>
  </div>
</header>
<body>


  <h2>収入</h2>
<% @income.each do |income| %>
  <table>
    <thead>
      <tr>
        <th>日付</th>
        <th>金額</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= income.register_day %></td>
          <td><%= income.income_amount %>円</td>
        </tr>
    </tbody>
  </table>
<% end %>
    <tr>
      <td><strong>合計</strong></td>
      <td><%= @income.sum(:income_amount) %>円</td>
    </tr>

<h2>支出</h2>
<% @expenditure.each do |expenditure| %>
  <table>
    <thead>
      <tr>
        <th>日付</th>
        <th>金額</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= expenditure.register_day %></td>
          <td><%= expenditure.expenditure_amount %>円</td>
        </tr>
    </tbody>
  </table>
<% end %>
    <tr>
      <td><strong>合計</strong></td>
      <td><%= @expenditure.sum(:expenditure_amount) %>円</td>
    </tr>

<h2>差額</h2>
<table>
  <thead>
    <tr>
      <th>日付</th>
      <th>差額</th>
    </tr>
  </thead>
  <tbody>

  </tbody>
</table>
</body>